; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27027.1 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG150524 DB	'c:\program_files\qtcreator\5.12.1\msvc2017_64\include\qt'
	DB	'core\qmetatype.h', 00H
	ORG $+7
$SG150525 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG150526 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG153523 DB	'c:\program_files\qtcreator\5.12.1\msvc2017_64\include\qt'
	DB	'core\qmetatype.h', 00H
	ORG $+7
$SG153524 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG153525 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG153864 DB	'c:\program_files\qtcreator\5.12.1\msvc2017_64\include\qt'
	DB	'core\qmetatype.h', 00H
	ORG $+7
$SG153865 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG153866 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG154205 DB	'c:\program_files\qtcreator\5.12.1\msvc2017_64\include\qt'
	DB	'core\qmetatype.h', 00H
	ORG $+7
$SG154206 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG154207 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_MainWindow@@3Uqt_meta_stringdata_MainWindow_t@@B DD 0ffffffffH ; qt_meta_stringdata_MainWindow
	DD	0aH
	DD	00H
	ORG $+4
	DQ	00000000000000f0H
	DD	0ffffffffH
	DD	04H
	DD	00H
	ORG $+4
	DQ	00000000000000e3H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	00000000000000d0H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	00000000000000b9H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	00000000000000b2H
	DD	0ffffffffH
	DD	09H
	DD	00H
	ORG $+4
	DQ	00000000000000adH
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	000000000000009fH
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	000000000000009aH
	DD	0ffffffffH
	DD	016H
	DD	00H
	ORG $+4
	DQ	0000000000000093H
	DD	0ffffffffH
	DD	016H
	DD	00H
	ORG $+4
	DQ	0000000000000092H
	DB	04dH
	DB	061H
	DB	069H
	DB	06eH
	DB	057H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	00H
	DB	06cH
	DB	06fH
	DB	06fH
	DB	070H
	DB	00H
	DB	00H
	DB	06cH
	DB	06fH
	DB	06fH
	DB	070H
	DB	041H
	DB	075H
	DB	074H
	DB	06fH
	DB	053H
	DB	06eH
	DB	061H
	DB	06bH
	DB	065H
	DB	04fH
	DB	06eH
	DB	065H
	DB	00H
	DB	06cH
	DB	06fH
	DB	06fH
	DB	070H
	DB	054H
	DB	068H
	DB	065H
	DB	053H
	DB	068H
	DB	06fH
	DB	072H
	DB	074H
	DB	065H
	DB	073H
	DB	074H
	DB	04fH
	DB	06eH
	DB	065H
	DB	00H
	DB	06cH
	DB	06fH
	DB	06fH
	DB	070H
	DB	050H
	DB	072H
	DB	069H
	DB	07aH
	DB	065H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	061H
	DB	075H
	DB	074H
	DB	06fH
	DB	06dH
	DB	061H
	DB	074H
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	068H
	DB	075H
	DB	06dH
	DB	061H
	DB	06eH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	073H
	DB	074H
	DB	061H
	DB	072H
	DB	074H
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	074H
	DB	068H
	DB	065H
	DB	053H
	DB	068H
	DB	06fH
	DB	072H
	DB	074H
	DB	065H
	DB	073H
	DB	074H
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	ORG $+7
	ORG $+8
?qt_meta_data_MainWindow@@3QBIB DD 08H			; qt_meta_data_MainWindow
	DD	00H
	DD	00H
	DD	00H
	DD	08H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	036H
	DD	02H
	DD	08H
	DD	03H
	DD	00H
	DD	037H
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	038H
	DD	02H
	DD	08H
	DD	05H
	DD	00H
	DD	039H
	DD	02H
	DD	08H
	DD	06H
	DD	00H
	DD	03aH
	DD	02H
	DD	08H
	DD	07H
	DD	00H
	DD	03bH
	DD	02H
	DD	08H
	DD	08H
	DD	00H
	DD	03cH
	DD	02H
	DD	08H
	DD	09H
	DD	00H
	DD	03dH
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@MainWindow@@UEBAPEBUQMetaObject@@XZ	; MainWindow::metaObject
PUBLIC	?qt_metacast@MainWindow@@UEAAPEAXPEBD@Z		; MainWindow::qt_metacast
PUBLIC	?qt_metacall@MainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; MainWindow::qt_metacall
PUBLIC	?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; MainWindow::qt_static_metacall
PUBLIC	?staticMetaObject@MainWindow@@2UQMetaObject@@B	; MainWindow::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?loop@MainWindow@@AEAAXXZ:PROC			; MainWindow::loop
EXTRN	?loopAutoSnakeOne@MainWindow@@AEAAXXZ:PROC	; MainWindow::loopAutoSnakeOne
EXTRN	?loopTheShortestOne@MainWindow@@AEAAXXZ:PROC	; MainWindow::loopTheShortestOne
EXTRN	?loopPrize@MainWindow@@AEAAXXZ:PROC		; MainWindow::loopPrize
EXTRN	?on_automat_clicked@MainWindow@@AEAAXXZ:PROC	; MainWindow::on_automat_clicked
EXTRN	?on_human_clicked@MainWindow@@AEAAXXZ:PROC	; MainWindow::on_human_clicked
EXTRN	?on_startButton_clicked@MainWindow@@AEAAXXZ:PROC ; MainWindow::on_startButton_clicked
EXTRN	?on_theShortest_clicked@MainWindow@@AEAAXXZ:PROC ; MainWindow::on_theShortest_clicked
EXTRN	__imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B:BYTE
EXTRN	__ImageBase:BYTE
_BSS	SEGMENT
?staticMetaObject@MainWindow@@2UQMetaObject@@B DB 030H DUP (?) ; MainWindow::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@MainWindow@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@MainWindow@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@MainWindow@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@MainWindow@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@MainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@MainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN16
	DD	imagerel $LN16+216
	DD	imagerel $unwind$?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@MainWindow@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@MainWindow@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@MainWindow@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@MainWindow@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@MainWindow@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@MainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@MainWindow@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@MainWindow@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'MainWindow::staticMetaObject'', COMDAT
; File c:\users\belka\desktop\qt\qtcreator\qt creator programy\wunsz\x64\debug\moc\moc_mainwindow.cpp
; Line 110
	mov	rax, QWORD PTR __imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B, rax
; Line 111
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_MainWindow@@3Uqt_meta_stringdata_MainWindow_t@@B
	mov	QWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+8, rax
; Line 112
	lea	rax, OFFSET FLAT:?qt_meta_data_MainWindow@@3QBIB
	mov	QWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+16, rax
; Line 113
	lea	rax, OFFSET FLAT:?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; MainWindow::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+24, rax
; Line 114
	mov	QWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+32, 0
; Line 115
	mov	QWORD PTR ?staticMetaObject@MainWindow@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@MainWindow@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'MainWindow::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; MainWindow::qt_static_metacall
; File c:\users\belka\desktop\qt\qtcreator\qt creator programy\wunsz\x64\debug\moc\moc_mainwindow.cpp
; Line 90
$LN16:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 91
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 92
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 94
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 7
	ja	SHORT $LN13@qt_static_
	movsxd	rax, DWORD PTR tv69[rsp]
	lea	rcx, OFFSET FLAT:__ImageBase
	mov	eax, DWORD PTR $LN15@qt_static_[rcx+rax*4]
	add	rax, rcx
	jmp	rax
$LN5@qt_static_:
; Line 95
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?loop@MainWindow@@AEAAXXZ		; MainWindow::loop
	jmp	SHORT $LN2@qt_static_
$LN6@qt_static_:
; Line 96
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?loopAutoSnakeOne@MainWindow@@AEAAXXZ	; MainWindow::loopAutoSnakeOne
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 97
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?loopTheShortestOne@MainWindow@@AEAAXXZ	; MainWindow::loopTheShortestOne
	jmp	SHORT $LN2@qt_static_
$LN8@qt_static_:
; Line 98
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?loopPrize@MainWindow@@AEAAXXZ		; MainWindow::loopPrize
	jmp	SHORT $LN2@qt_static_
$LN9@qt_static_:
; Line 99
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_automat_clicked@MainWindow@@AEAAXXZ	; MainWindow::on_automat_clicked
	jmp	SHORT $LN2@qt_static_
$LN10@qt_static_:
; Line 100
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_human_clicked@MainWindow@@AEAAXXZ	; MainWindow::on_human_clicked
	jmp	SHORT $LN2@qt_static_
$LN11@qt_static_:
; Line 101
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_startButton_clicked@MainWindow@@AEAAXXZ ; MainWindow::on_startButton_clicked
	jmp	SHORT $LN2@qt_static_
$LN12@qt_static_:
; Line 102
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_theShortest_clicked@MainWindow@@AEAAXXZ ; MainWindow::on_theShortest_clicked
$LN13@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 107
	add	rsp, 56					; 00000038H
	ret	0
	npad	2
$LN15@qt_static_:
	DD	$LN5@qt_static_
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN8@qt_static_
	DD	$LN9@qt_static_
	DD	$LN10@qt_static_
	DD	$LN11@qt_static_
	DD	$LN12@qt_static_
?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; MainWindow::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@MainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; MainWindow::qt_metacall
; File c:\users\belka\desktop\qt\qtcreator\qt creator programy\wunsz\x64\debug\moc\moc_mainwindow.cpp
; Line 133
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 134
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 135
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 136
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 137
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 138
	cmp	DWORD PTR _id$[rsp], 8
	jge	SHORT $LN5@qt_metacal
; Line 139
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@MainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; MainWindow::qt_static_metacall
$LN5@qt_metacal:
; Line 140
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 8
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 141
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 142
	cmp	DWORD PTR _id$[rsp], 8
	jge	SHORT $LN7@qt_metacal
; Line 143
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 144
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 8
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 146
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 147
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@MainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; MainWindow::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@MainWindow@@UEAAPEAXPEBD@Z PROC		; MainWindow::qt_metacast
; File c:\users\belka\desktop\qt\qtcreator\qt creator programy\wunsz\x64\debug\moc\moc_mainwindow.cpp
; Line 125
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 126
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 127
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_MainWindow@@3Uqt_meta_stringdata_MainWindow_t@@B+240
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 128
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 129
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 130
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@MainWindow@@UEAAPEAXPEBD@Z ENDP		; MainWindow::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@MainWindow@@UEBAPEBUQMetaObject@@XZ PROC	; MainWindow::metaObject
; File c:\users\belka\desktop\qt\qtcreator\qt creator programy\wunsz\x64\debug\moc\moc_mainwindow.cpp
; Line 120
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 121
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@MainWindow@@2UQMetaObject@@B ; MainWindow::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 122
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@MainWindow@@UEBAPEBUQMetaObject@@XZ ENDP	; MainWindow::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File c:\program_files\qtcreator\5.12.1\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File c:\users\belka\desktop\qt\qtcreator\qt creator programy\wunsz\x64\debug\moc\moc_mainwindow.cpp
; Line 150
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File c:\users\belka\desktop\qt\qtcreator\qt creator programy\wunsz\x64\debug\moc\moc_mainwindow.cpp
; Line 150
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
